# .goreleaser.yml
# Build customization
builds:
  - main: cmd/undocker/main.go
    binary: undocker
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

# brews:
#   - name: undocker
#     github:
#       owner: tokibi
#       name: homebrew-tap
#     homepage: "https://github.com/tokibi/undocker/"
#     description: "a tool for decomposing docker images."
#     test: |
#       system "#{bin}/undocker --version"
#     install: |
#       bin.install "undocker"
